language: python

python:
  - 2.7

install:
  - pip install -r requirements.txt
  - pip install pycodestyle

script:
  - python manage.py flush --noinput
  - python manage.py makemigrations
  - python manage.py migrate --noinput
  - python manage.py test
  - pycodestyle --count --show-source --exclude=migrations .
