# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-05 04:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='x_position',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='entity',
            name='y_position',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='entity',
            name='z_position',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='human',
            name='gender',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='human',
            name='person_name',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='object',
            name='color',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='object',
            name='type',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
