# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-11 00:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20170705_0411'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('x1', models.FloatField()),
                ('x2', models.FloatField()),
                ('x3', models.FloatField()),
                ('x4', models.FloatField()),
                ('y1', models.FloatField()),
                ('y2', models.FloatField()),
                ('y3', models.FloatField()),
                ('y4', models.FloatField()),
                ('room_name', models.CharField(max_length=50)),
                ('entity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Entity')),
            ],
        ),
    ]
