# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-05 03:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_waypoint'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArTag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ar_id', models.IntegerField(null=True)),
                ('entity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Entity')),
            ],
        ),
    ]
